### ISSUE TITLE
Verification, GDS as artifact

### ISSUE THREAD

**Issue by lukasc-ubc** [SiEPIC/openEBL-2024-02#12]
@jasminabrar 
If you submit a Python file, the artifact is the lyrbd file, but the GDS/OAS is not included. Can we add the resulting layout binary file as part of the artifact?
thank you

**Comment by jasminabrar** [comment]
This has now been added. The GDS/OAS are uploaded as an artifact in the 'Run Python Files' action. I think it makes most sense to upload them in this action (instead of the in the verification action) since this action is solely responsible for running the python files and generating the oas/gds file. It also allowed me to get rid of the python_to_oas_gds.txt file that was previously accessed in the verification action in the case when the verification action is triggered by the python action. Instead of reading the generated oas/gds names from the txt file, now I simply get the oas/gds files from the artifact.

**Comment by jasminabrar** [comment]
This issue can now be closed.
